theme: jekyll-theme-architect

title: [metro-ws-test-harness]
description: [subproject of jax-ws: JAX-WS test harness ]

# sidebar links url
links:
  source: https://github.com/javaee/metro-ws-test-harness
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

